name: Select A1 in Excel Sheets

on:
  push:
    branches:
      - main

jobs:
  select-a1-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl

    - name: Run Python script
      run: |
        python select_a5.py
